ManagementSys/src/main/java/ch/guggisberg/stefan/classController/ClassController.java
package ch.guggisberg.stefan.classController;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.Kurs;
import ch.guggisberg.stefan.groupfitness.course.services.ClassService;

@Named
@SessionScoped
public class ClassController extends BaseBean implements Serializable {
	private static final long serialVersionUID = 3263438832673772158L;

	@EJB
	private ClassService cs;

	private Kurs kurs = new Kurs();

	//NAV
	
	private static final String NAVIGATE_TO_CLASSES_LIST = "/grpAdmin/classViews/classesList";

	public List<Kurs> getFilteredClasses(){
		return cs.getFilteredClasses(filter);
	}

	public String search() {
		return NAVIGATE_TO_CLASSES_LIST;
	}

	public String editView(Kurs k) {
		kurs = cs.find(Kurs.class, k.getId());
		return NAVIGATE_TO_CLASSES_LIST;
	}

	public String update() {
		kurs= cs.updateKurs(kurs);
		showGlobalMessage("messages.class.changes");
		return NAVIGATE_TO_CLASSES_LIST;
	}

	
	public String deleteView(Kurs k) {
		cs.remove(k.getId());
		showGlobalMessage("messages.class.deleted");
		return NAVIGATE_TO_CLASSES_LIST;
	}

	public String createKurs() {
		showGlobalMessage("messages.class.created");
		kurs = cs.createKurs(kurs);
		
		return NAVIGATE_TO_CLASSES_LIST;
	}
	// Getter / Setter

	public Kurs getKurs() {
		return kurs;
	}

	public void setKurs(Kurs kurs) {
		this.kurs = kurs;
	}
	public Kurs getKursById(Long id) {
		return cs.getKursById(id);
	}

	



}

ManagementSys/src/main/webapp/grpAdmin/classTypViews/classesList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.class']}</ui:define>
		<ui:define name="content">

			<div class="container"
				mx-autostyle="max-width: 600px; background: #ebeff2">
				<h2>
					<h:outputText value="#{msg['list.title.class']}" />
				</h2>
				
				<div>

					<!--  Such Feld -->
					<div class="filter">
						<h:form class="form-inline mt-2 mt-md-0">
							<h:inputText class="form-control mr-sm-2" type="text"
								pt:placeholder="Search" aria-label="Search"
								value="#{classController.filter}" />
							<h:commandButton action="#{classController.search}"
								value="Filtern"
								styleClass="btn btn-outline-success my-2 my-sm-0" />
						</h:form>
					</div>

				</div>
				<!-- Tabelle -->
				<table class="table tablesorter" id="sortedTable">

					<thead class="thead-dark">
						<tr>
							<th scope="col"><h:outputText
									value="#{msg['form.new.class.typ.name.de']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['form.new.class.typ.name.fr']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['form.new.class.typ.name.desc.de']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['form.new.class.typ.name.desc.fr']}" /></th>
							<th class="sorter-false"></th>
							<th class="sorter-false"></th>
						</tr>
					</thead>
					<tbody>
						<h:form>
							<c:forEach var="kurs" items="#{classController.filteredClasses}">
								<tr>
									<td><h:outputText value="#{kurs.nameDe}" /></td>
									<td><h:outputText value="#{kurs.nameFr}" /></td>
									<td><h:outputText value="#{kurs.descDe}" /></td>
									<td><h:outputText value="#{kurs.descFr}" /></td>
									<td><h:commandLink immediate="true" styleClass=""
											action="#{classController.editView(kurs)}">
											<i class="material-icons"> edit </i>
										</h:commandLink></td>
									<td><h:commandLink
											onclick="if (! confirm('#{msg['infos.sure']}')) return false"
											immediate="true" styleClass=""
											action="#{classController.deleteView(kurs)}">
											<i class="material-icons"> delete </i>


										</h:commandLink></td>
								</tr>
							</c:forEach>
						</h:form>

					</tbody>
				</table>
			</div>
		</ui:define>

	</ui:composition>

</h:body>
</html>

ManagementSys/src/main/webapp/grpAdmin/classTypViews/createClassType.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['form.new.title.class']}</ui:define>
		<ui:define name="content">
			<div class="container">
				<h2><h:outputText value="#{msg['form.new.title.class']}" /></h2>

				<div>
					<h:form class="form-horizontal" role="form">
						<div class="form-group">
							<label for="nameDe" class="control-label col-sm-3"><h:outputText value="#{msg['form.new.class.typ.name.de']}" /></label>

							<h:inputText type="text" class="form-control" id="nameDe"
								value="#{classController.kurs.nameDe}" pt:placeholder="#{msg['form.new.class.typ.name.de']}" />
							<h:message for="nameDe" style="color:red" />
						</div>

						<div class="form-group">
							<label for="descDe" class="control-label col-sm-3"><h:outputText value="#{msg['form.new.class.typ.name.desc.de']}" /></label>
							<h:inputText type="text" class="form-control" id="descDe"
								value="#{classController.kurs.descDe}" pt:placeholder="#{msg['form.new.class.typ.name.desc.de']}" />
							<h:message for="descDe" style="color:red" />
						</div>

						<div class="form-group">
							<label for="nameFr" class="control-label col-sm-3"><h:outputText value="#{msg['form.new.class.typ.name.fr']}" /></label>
							<h:inputText type="text" class="form-control" id="nameFr"
								value="#{classController.kurs.nameFr}" pt:placeholder="#{msg['form.new.class.typ.name.fr']}" />
							<h:message for="nameFr" style="color:red" />


							<div class="form-group">
								<label for="descFr" class="control-label col-sm-3"><h:outputText value="#{msg['form.new.class.typ.name.desc.fr']}" /></label>
								<h:inputText type="text" class="form-control" id="descFr"
									value="#{classController.kurs.descFr}" pt:placeholder="#{msg['form.new.class.typ.name.desc.fr']}" />
								<h:message for="descFr" style="color:red" />
							</div>

						</div>

						<div>
							<h:commandButton action="#{classController.createKurs}"
								value="#{msg['form.button.create']}"
								styleClass="btn btn-primary btn-lg btn-block button" />
						</div>

					</h:form>
				</div>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>