ManagementSys/src/main/java/ch/guggisberg/stefan/financeController/ERPExporterController.java
package ch.guggisberg.stefan.financeController;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.MonthlyPayroll;
import ch.guggisberg.stefan.groupfitness.course.model.State;
import ch.guggisberg.stefan.groupfitness.course.services.MonthlyPayrollService;
import ch.guggisberg.stefan.utils.file.ERPFileGenerator;

@Named
@RequestScoped
public class ERPExporterController  extends BaseBean implements Serializable {

	private static final long serialVersionUID = -7423034487445810161L;

	private static Logger log = Logger.getLogger(ERPExporterController.class);
	private ERPFileGenerator erpFileGenerator;

	@EJB
	private MonthlyPayrollService mps;

	private List<MonthlyPayroll> monthlyPayroll;

	
	//NAV
	
	private static final String NAVIGATE_TO_ERP_EXPORTER_VIEW = "/finance/exportViews/ERPExporterView";
	
	// Transaction!
	public String export() {
		erpFileGenerator = new ERPFileGenerator(monthlyPayroll);
		try {
			for (MonthlyPayroll payItem : monthlyPayroll) {
				payItem.setState(State.exported);
				mps.update(payItem);
			}
			erpFileGenerator.generateTheExportFile();
				showGlobalMessage(("messages.finance.download.started"));
		} catch (IOException e) {
			log.error(e);
			showGlobalErrorMessage("error.messages.hopla");
		}
		return NAVIGATE_TO_ERP_EXPORTER_VIEW;
	}

	/**
	 * Liefert die Stundenblätter mit dem Status exporting.
	 * Ready to export!
	 * 
	 * @return List<MonthlyPayroll> - zu exportieren
	 */
	public List<MonthlyPayroll> getPayRollList(){
		monthlyPayroll = mps.getVerifyList(State.ready2export);
		return monthlyPayroll;
	}

	public List<MonthlyPayroll> getMonthlyPayroll() {
		return monthlyPayroll;
	}

	public void setMonthlyPayroll(List<MonthlyPayroll> monthlyPayroll) {
		this.monthlyPayroll = monthlyPayroll;
	}



}

ManagementSys/src/main/java/ch/guggisberg/stefan/financeController/FinanceController.java
package ch.guggisberg.stefan.financeController;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.ClassRun;
import ch.guggisberg.stefan.groupfitness.course.entities.MonthlyPayroll;
import ch.guggisberg.stefan.groupfitness.course.model.State;
import ch.guggisberg.stefan.groupfitness.course.services.MonthlyPayrollService;
import ch.guggisberg.stefan.groupfitness.course.services.PersonService;

@Named
@SessionScoped
public class FinanceController extends BaseBean implements Serializable {

	private static final long serialVersionUID = 174999736345493347L;

	@EJB
	private MonthlyPayrollService mps;
	
	@EJB
	private PersonService ps;
	
	private MonthlyPayroll monthlyPayroll;
	private List<ClassRun> classRuns;
	
	//NAV
	
	private static final String NAVIGATE_TO_MONTHLY_PAYROLL_DETAIL_VIEW = "/finance/payrollViews/monthlyPayrollDetailView";
	private static final String NAVIGATE_TO_FINANCE_VIEW = "/finance/financeView";
			
	public String verifyDetailView (MonthlyPayroll monthlyPayroll) {
		this.monthlyPayroll = mps.getMonthlyPayroll(monthlyPayroll.getId());
		this.classRuns=monthlyPayroll.getClassRuns();
		return NAVIGATE_TO_MONTHLY_PAYROLL_DETAIL_VIEW;
	}
	
	public String reject() {
		monthlyPayroll.setState(State.rejected);
		mps.update(monthlyPayroll);
		showGlobalMessage(("messages.finance.payroll.rejeacted"));
		return NAVIGATE_TO_FINANCE_VIEW;
	}
	
	public String book() {
		monthlyPayroll.setState(State.ready2export);
		mps.update(monthlyPayroll);
		showGlobalMessage(("messages.finance.ready2export"));
		return NAVIGATE_TO_FINANCE_VIEW;
	}
	

// Getter / Setter

	
	public List<ClassRun> getClasses(){
		return classRuns;
	}
	
	public List<MonthlyPayroll> getPayRollList(){
		return mps.getVerifyList(State.approved);
	}


	public MonthlyPayroll getMonthlyPayroll() {
		return monthlyPayroll;
	}


	public void setMonthlyPayroll(MonthlyPayroll monthlyPayroll) {
		this.monthlyPayroll = monthlyPayroll;
	}
	
	
}

ManagementSys/src/main/webapp/finance/exportViews/ERPExporterView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:include src="/templates/search.xhtml" />
		<ui:define name="title">#{msg['detail.title.monthly.graduation']}"</ui:define>
		<ui:define name="content">
			<div class="container">
				<div class="col">
					<h2>
						<h:outputText value="#{msg['detail.title.monthly.graduation']}" />
					</h2>

				</div>
				<h:form>

					<div>
						<h3>Hier findest du die Stundenblätter, die zum Exporter
							bereit sind.</h3>
					</div>

					<!-- Exportieren -->
					<div class="alert alert-info">

						<h:commandButton action="#{eRPExporterController.export()}"
							value="#{msg['detail.view.export']}"
							styleClass="btn btn-outline-success form-check-inline "
							immediate="true" />
					</div>
				</h:form>
				<!-- Tabelle -->
				<table class="table tablesorter" id="sortedTable">

					<thead class="thead-dark">
						<tr>
							<th scope="col"><h:outputText
									value="#{msg['form.new.instructor.name']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['form.new.instructor.firstname']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['form.new.instructor.email']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['list.verify.person.delivery.date']}" /></th>
							<th class="sorter-false"></th>
							<th class="sorter-false"></th>


						</tr>
					</thead>
					<tbody>
						<h:form>
							<c:forEach var="payRoll"
								items="#{eRPExporterController.payRollList}">
								<tr>
									<td><h:outputText value="#{payRoll.person.name}" /></td>
									<td><h:outputText value="#{payRoll.person.firstName}" /></td>
									<td><h:outputText value="#{payRoll.person.email}" /></td>
									<td><h:outputText value="#{payRoll.date}" /></td>

									<td></td>
									<td></td>
								</tr>

							</c:forEach>
						</h:form>

					</tbody>
					<tfoot>

						<tr>
							<td>Total</td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</tfoot>
				</table>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>