ManagementSys/src/main/java/ch/guggisberg/stefan/classRunController/ClassRunController.java
package ch.guggisberg.stefan.classRunController;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.ClassRun;
import ch.guggisberg.stefan.groupfitness.course.entities.Kurs;
import ch.guggisberg.stefan.groupfitness.course.entities.Person;
import ch.guggisberg.stefan.groupfitness.course.entities.Room;
import ch.guggisberg.stefan.groupfitness.course.exceptions.DayOfWeekOutOfRangeException;
import ch.guggisberg.stefan.groupfitness.course.exceptions.StartDateHigherThanEndDateException;
import ch.guggisberg.stefan.groupfitness.course.services.ClassRunService;
import ch.guggisberg.stefan.groupfitness.course.services.ClassService;
import ch.guggisberg.stefan.groupfitness.course.services.PersonService;
import ch.guggisberg.stefan.groupfitness.course.services.RoomService;
import ch.guggisberg.stefan.groupfitness.course.utils.DateGenerator;


@Named
@SessionScoped
public class ClassRunController extends BaseBean implements Serializable {

	private static final long serialVersionUID = 6962723803915463465L;
	private static Logger log = Logger.getLogger(ClassRunController.class);

	private static final DayOfWeek[] DAY_OF_WEEK = DayOfWeek.values();

	@EJB
	private ClassService cs;

	@EJB
	private PersonService ps;

	@EJB
	private ClassRunService crs;

	@EJB
	private RoomService rs;

	private ClassRun classRun;
	private Set<ClassRun> multiClassRuns;
	private Set<LocalDate> multidates;
	private DateGenerator dg;

	private Date startDate;
	private Date endDate;
	private String startTime;
	private int duration;
	private int day;

	private Long personId;
	private Long roomId;
	private Long classtypId;
	
	//NAV
	
	private static final String NAVIGATE_TO_CLASS_RUN_MULTI_PREVIEW_LIST = "/grpAdmin/classRunViews/classRunMultiPreViewList";
	private static final String NAVIGATE_TO_CLASS_RUN_LIST = "/grpAdmin/classRunViews/classRunsList";
	private static final String NAVIGATE_TO_CLASS_RUN_EDIT = "/grpAdmin/classRunViews/classRunEdit";

	public String createMultiClassRun() throws ParseException {
		multiClassRuns =  new HashSet<>();
		multidates = new HashSet<>();
		dg = new DateGenerator();
		try {
			multidates = dg.getAllDays(startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), day);
		} catch (StartDateHigherThanEndDateException e) {
			showGlobalErrorMessage("error.messages.startdate.older");
			log.info("Das Start Datum ist nach dem End Datum");
		} catch (DayOfWeekOutOfRangeException e) {
			// Sollte nicht passieren können. Da ist beim Client was schief gelaufen
			showGlobalErrorMessage("error.messages.hopla");
			log.error("User hat einen falschen Wochentag, ausserhalb von 1-7 ausgewählt");
		}

		for (LocalDate singleDate : multidates) {

			preCreateClassRun();
			classRun.setDate(singleDate);
			multiClassRuns.add(classRun);
		}

		return NAVIGATE_TO_CLASS_RUN_MULTI_PREVIEW_LIST;
	}
	public String createFromPreview() {
		for (ClassRun classRun : multiClassRuns) {
			crs.createClassRun(classRun);
		}
		showGlobalMessage("messages.class.run.created.multi");
		return NAVIGATE_TO_CLASS_RUN_LIST;
	}


	public void createClassRun() throws ParseException {
		preCreateClassRun();
		classRun.setDate(startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
		crs.createClassRun(classRun);
		showGlobalMessage("messages.class.run.created.single");
	}

	private void preCreateClassRun() {
		classRun = new ClassRun();
		Room room= rs.getRoom(roomId);
		Person person = ps.getPerson(personId);
		classRun.setStartTime((LocalTime.parse(startTime)));
		classRun.setRoom(room);
		classRun.setPerson(person);
		classRun.setDuration(duration);
		classRun.setKurs(cs.getKurs(classtypId));
	}

	public Set<ClassRun> getPreviewClassRuns(){
		return multiClassRuns;
	}

	public String removeClassRun(ClassRun cr) {
		multiClassRuns.remove(cr);
		return NAVIGATE_TO_CLASS_RUN_MULTI_PREVIEW_LIST;
	}

	public String editClassRun(ClassRun cr) {
		classRun= crs.getClassRunById(cr.getId());
		return NAVIGATE_TO_CLASS_RUN_EDIT;
	}
	
	public String deleteClassRun(ClassRun cr) {
		crs.delete(cr);
		showGlobalMessage("messages.class.run.deleted");
		return NAVIGATE_TO_CLASS_RUN_LIST;
	}
	
	public String updateClassRun(ClassRun cr) {
		crs.update(cr);
		showGlobalMessage("messages.class.run.mod");
		return NAVIGATE_TO_CLASS_RUN_LIST;
	}
	
	// Getter / Setter

	public ClassRun getClassRun() {
		return classRun;
	}

	public void setClassRun(ClassRun classRun) {
		this.classRun = classRun;
	}

	public List<Person> getAllPerson(){
		return ps.getAllPersons();
	}

	public List<Kurs> getAllClasses(){
		return cs.getFilteredClasses("");
	}

	public List<Room> getAllRooms(){
		return rs.getAllRooms(); 
	}

	public List<ClassRun> getAllClassRuns(){
		return crs.getAllClassRuns();
	}

	public int getDuration() {
		return duration;
	}


	public void setDuration(int duration) {
		this.duration = duration;
	}


	public Long getPersonId() {
		return personId;
	}


	public void setPersonId(Long personId) {
		this.personId = personId;
	}


	public Long getRoomId() {
		return roomId;
	}


	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}


	public Long getClasstypId() {
		return classtypId;
	}


	public void setClasstypId(Long classtypId) {
		this.classtypId = classtypId;
	}


	public Date getStartDate() {
		return startDate;
	}


	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}


	public String getStartTime() {
		return startTime;
	}


	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}


	public DayOfWeek[] getDayOfWeeks() {
		return DAY_OF_WEEK;
	}

	public Date getEndDate() {
		return endDate;
	}


	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}


	public int getDay() {
		return day;
	}

	public void setDay(int day) {
		this.day = day;
	}


}

ManagementSys/src/main/java/ch/guggisberg/stefan/roomController/RoomController.java
package ch.guggisberg.stefan.roomController;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.Room;
import ch.guggisberg.stefan.groupfitness.course.services.RoomService;

@Named
@SessionScoped
public class RoomController extends BaseBean implements Serializable{

	private static final long serialVersionUID = -2626759258838436056L;

	private Room room = new Room();
	
	@EJB
	private RoomService rs;

	

	//NAV

	private static final String NAVIGATE_TO_ROOM_LIST = "/grpAdmin/roomViews/roomList";
	
	
	public void createRoom() {
		showGlobalMessage("messages.room.created");
		rs.createKurs(room);
		room=null;
	}
	public List<Room> getAllRooms(){
		return rs.getAllRooms();
	}

	public String deleteView(Room r) {
		rs.remove(r.getId());
		showGlobalMessage("messages.room.deleted");
		room=null;
		return NAVIGATE_TO_ROOM_LIST;
	}
	
	public String editView(Room r) {
		this.room = rs.find(Room.class, r.getId());
		room=null;
		return "/grpAdmin/roomViews/roomEdit";
	}

	public String update() {
		room= rs.update(room);
		showGlobalMessage("messages.room.mod");
		room=null;
		return NAVIGATE_TO_ROOM_LIST;
	}


	// Getter / Setter

	public Room getRoom() {
		return room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}
}

ManagementSys/src/main/java/ch/guggisberg/stefan/userController/UserController.java
package ch.guggisberg.stefan.userController;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.List;
import java.util.Locale;

import javax.ejb.EJB;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.apache.log4j.Logger;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.Person;
import ch.guggisberg.stefan.groupfitness.course.exceptions.NewPasswordsMisMachtesException;
import ch.guggisberg.stefan.groupfitness.course.exceptions.PasswordWrongException;
import ch.guggisberg.stefan.groupfitness.course.services.ClassService;
import ch.guggisberg.stefan.groupfitness.course.services.PersonService;

@Named
@SessionScoped
@TransactionAttribute(TransactionAttributeType.REQUIRED)
public class UserController extends BaseBean implements Serializable{
	private static final long serialVersionUID = 4120644572130464132L;
	private static Logger log = Logger.getLogger(UserController.class);

	private Person person = new Person();

	
	//NAV

	private static final String NAVIGATE_TO_USER_LIST = "/grpAdmin/userViews/userList";
	private static final String NAVIGATE_TO_USER_EDIT = "/grpAdmin/userViews/userEdit";
	
		
	@EJB
	private PersonService ps;
	
	@EJB
	private ClassService cs;

	@Pattern(regexp = "^[A-Za-z0-9äÄöÖüÜ]+$")
	@Size(min=1, max=45)
	private String newPassword;

	@Pattern(regexp = "^[A-Za-z0-9äÄöÖüÜ]+$")
	@Size(min=1, max=45)
	private String newRepeatedPassword;

	@Pattern(regexp = "^[A-Za-z0-9äÄöÖüÜ]+$")
	@Size(min = 1, max=45)
	private String oldPassword;

	@Pattern(regexp = "^(DE|FR)$")
	@Size(min = 2, max=2)
	private String lang;

	public String createUser() {
		showGlobalMessage(MessageFormat.format("messages.user.created", person.getFirstName()));
		ps.createPerson(person);
		person=null;
		return NAVIGATE_TO_USER_LIST;
	}

	public String deleteView(Person p) {
		ps.remove(p.getId());
		showGlobalMessage("messages.user.deleted");
		return NAVIGATE_TO_USER_LIST;
	}

	public String update() {
		person= ps.updatePerson(person);
		showGlobalMessage("messages.user.changed");
		return NAVIGATE_TO_USER_LIST;
	}

	public String editView(Person p) {
		this.person = ps.find(Person.class, p.getId());
		return NAVIGATE_TO_USER_EDIT;
	}

	public String search() {
		return NAVIGATE_TO_USER_LIST;
	}

	/**
	 * Ändert das Kennwort
	 * @return
	 */
	public String changePassword() {
		try {
			ps.changePassword(newPassword, newRepeatedPassword, oldPassword);
			showGlobalMessage("messages.user.password.changed");
		} catch (NewPasswordsMisMachtesException e) {
			showGlobalErrorMessage("messages.user.password.doesnt.match");
			log.info(e);
		} catch (PasswordWrongException e) {
			showGlobalErrorMessage("messages.user.password.wrong");
			log.info(e);
		}
		oldPassword = "";
		newPassword = "";
		newRepeatedPassword = "";
		return "/person/settings";
	}

	/**
	 * Ändert die Sprache in Faces Context sowie auf der DB.
	 * @return
	 */
	public String changeLang() {
		person = ps.getLoggedPerson();
		if (lang == null ||lang.equals("de")) {
			FacesContext.getCurrentInstance().getViewRoot().setLocale(Locale.GERMAN);
		}
		else {
			FacesContext.getCurrentInstance().getViewRoot().setLocale(Locale.FRENCH);
		}
		person.setLanguage(lang);
		person = ps.update(person);
		showGlobalMessage("messages.user.lang.changed");
		return "/person/settings";
	}


	// Gette Setter
	public Person getPerson() {
		return person;
	}
	public void setPerson(Person person) {
		this.person = person;	
	}

	public List<Person> getFilteredPersons(){
		return ps.getFilteredPersons(filter);
	}

	public List<Person> getAllPerson(){
		return ps.getAllPersons();
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	public String getNewRepeatedPassword() {
		return newRepeatedPassword;
	}

	public void setNewRepeatedPassword(String newRepeatedPassword) {
		this.newRepeatedPassword = newRepeatedPassword;
	}

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}

ManagementSys/src/main/webapp/grpAdmin/classRunViews/classRunEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:include src="/templates/search.xhtml" />
		<ui:define name="title">#{msg['form.edit.title.class']}</ui:define>
		<ui:define name="content">
			<div class="container">

				<div class="col">
					<h2>#{msg['form.edit.title.class']}</h2>
				</div>

				<div class="col">
										<h:form class="form-horizontal" role="form">

						<!-- Kurs Typ -->
						<div class="form-group">
							<label for="typ" class="control-label col-sm-3">#{msg['form.new.class.run.kurs.typ']}</label>
							<h:selectOneMenu value="#{classRunController.classtypId}"
								required="true" styleClass="form-control" id="typ">
								<f:selectItem itemValue="#{null}" itemLabel="-- Kurs --" />
								<f:selectItems value="#{classRunController.allClasses}" var="c"
									itemLabel="#{c.nameDe} " itemValue="#{c.id}" />
							</h:selectOneMenu>
							<h:message for="typ" style="color:red" />
						</div>

						<!-- Instruktor -->
						<div class="form-group">
							<label for="person" class="control-label col-sm-3">#{msg['form.new.class.run.instructor']}</label>
							<h:selectOneMenu value="#{classRunController.personId}"
								required="true" styleClass="form-control" id="person">
								<f:selectItem itemValue="#{null}" itemLabel="-- Instruktor --" />
								<f:selectItems value="#{classRunController.allPerson}" var="p"
									itemLabel="#{p.email} | #{p.name} | #{p.firstName}"
									itemValue="#{p.id}" />
							</h:selectOneMenu>
							<h:message for="person" style="color:red" />
						</div>

						<!-- Kurs Raum -->
						<div class="form-group">
							<label for="room" class="control-label col-sm-3">#{msg['form.new.class.run.room']}</label>
							<h:selectOneMenu value="#{classRunController.roomId}"
								required="true" styleClass="form-control" id="room">
								<f:selectItem itemValue="#{null}" itemLabel="-- Raum --" />
								<f:selectItems value="#{classRunController.allRooms}" var="r"
									itemLabel="#{r.nameDe}" itemValue="#{r.id}" />
							</h:selectOneMenu>
							<h:message for="room" style="color:red" />
						</div>

						<!-- Start Datum -->
						<div class="form-group">
							<label for="start" class="control-label col-sm-3">#{msg['form.new.class.run.start.date']}</label>
							<h:inputText pt:type="date" id="start" name="trip-start"
								value="#{classRunController.startDate}" min="2018-01-01"
								max="2022-12-31" styleClass="form-control">
								<f:validateRequired />
								<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
							</h:inputText>
							<h:message for="start" style="color:red" />
						</div>

						<!-- Start Zeit -->
						<div class="form-group">
							<label for="time" class="control-label col-sm-3"><h:outputText
									value="#{msg['form.new.class.run.start.time']}" /></label>
							<h:inputText type="time" class="form-control" id="time"
								value="#{classRunController.startTime}"
								pt:placeholder="#{msg['form.new.class.run.start.time']}">
								<f:validateRegex
									pattern="^$|^(([01][0-9])|(2[0-3])):[0-5][0-9]$" />
								<f:validateRequired />
							</h:inputText>
							<h:message for="time" style="color:red" />
						</div>

						<!-- Dauer -->
						<div class="form-group">
							<label for="duration" class="control-label col-sm-3"><h:outputText
									value="#{msg['form.new.class.run.duration']}" /></label>
							<h:inputText type="time" class="form-control" id="duration"
								value="#{classRunController.duration}"
								pt:placeholder="#{msg['form.new.class.run.start.duration']}">
								<f:validateLongRange minimum="5" maximum="300" />
								<f:validateRequired />
							</h:inputText>
							<h:message for="duration" style="color:red" />
						</div>

						<div>
							<h:commandButton action="#{classRunController.updateClassRun}"
								value="#{msg['form.button.create']}"
								styleClass="btn btn-primary btn-lg btn-block button" />
						</div>

					</h:form>
				</div>
			</div>



		</ui:define>
	</ui:composition>
</h:body>
</html>

ManagementSys/src/main/webapp/grpAdmin/classRunViews/classRunMultiPreViewList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.class']}</ui:define>
		<ui:define name="content">

			<div class="container"
				mx-autostyle="max-width: 600px; background: #ebeff2">
				<h2>
					<h:outputText value="#{msg['list.title.class']}" />
				</h2>

				<h:form class="form-inline mt-2 mt-md-0">

					<div>

						<!--  Such Save  -->
						<div class="filter">

							<h:commandButton
								action="#{classRunController.createFromPreview()}"
								value="Alle speichern"
								styleClass="btn btn-outline-success my-2 my-sm-0" />
						</div>
					</div>
					<!-- Tabelle -->
					<table class="table">
						<tbody>
							<thead class="thead-dark">
								<tr>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.start.date']}" /></th>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.start.time']}" /></th>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.duration']}" /></th>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.kurs.typ']}" /></th>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.instructor']}" /></th>
									<th scope="col"><h:outputText
											value="#{msg['form.new.class.run.room']}" /></th>
									<th></th>
								</tr>
							</thead>

							<c:forEach var="classrun"
								items="#{classRunController.previewClassRuns}">
								<tr>
									<td><h:outputText value="#{classrun.date}" /></td>
									<td><h:outputText value="#{classrun.startTime}" /></td>
									<td><h:outputText value="#{classrun.duration}" /></td>
									<td><h:outputText value="#{classrun.kurs.nameDe}" /></td>

									<!-- Person -->
									<td><h:selectOneMenu value="#{classrun.person.id}"
											required="true" styleClass="form-control" id="person">
											<f:selectItems value="#{classRunController.allPerson}"
												var="p" itemLabel="#{p.email} | #{p.name} | #{p.firstName}"
												itemValue="#{p.id}" />
										</h:selectOneMenu> <h:message for="person" style="color:red" /></td>

									<!-- Kurs Raum -->
									<td><h:selectOneMenu value="#{classrun.room.id}"
											required="true" styleClass="form-control" id="room">
											<f:selectItems value="#{classRunController.allRooms}" var="r"
												itemLabel="#{r.nameDe}" itemValue="#{r.id}" />
										</h:selectOneMenu> <h:message for="room" style="color:red" /></td>


									<td><h:commandLink immediate="true" styleClass=""
											action="#{classRunController.removeClassRun(classrun)}">
											<i class="material-icons"> delete </i>
										</h:commandLink></td>
								</tr>
							</c:forEach>


						</tbody>
					</table>
				</h:form>
			</div>
		</ui:define>

	</ui:composition>

</h:body>
</html>

ManagementSys/src/main/webapp/grpAdmin/classRunViews/createClassRunMulti.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['form.new.title.class.run.multi']}"</ui:define>
		<ui:define name="content">
			<div class="container">
				<h2>
					<h:outputText value="#{msg['form.new.title.class.run.multi']}" />
				</h2>

				<div>
					<h:form class="form-horizontal" role="form">

						<!-- Kurs Typ -->
						<div class="form-group">
							<label for="typ" class="control-label col-sm-3">#{msg['form.new.class.run.kurs.typ']}</label>
							<h:selectOneMenu value="#{classRunController.classtypId}"
								required="true" styleClass="form-control" id="typ">
								<f:selectItem itemValue="#{null}" itemLabel="-- Kurs --" />
								<f:selectItems value="#{classRunController.allClasses}" var="c"
									itemLabel="#{c.name} " itemValue="#{c.id}" />
							</h:selectOneMenu>
							<h:message for="typ" style="color:red" />
						</div>

						<!-- Instruktor -->
						<div class="form-group">
							<label for="person" class="control-label col-sm-3">#{msg['form.new.class.run.instructor']}</label>
							<h:selectOneMenu value="#{classRunController.personId}"
								required="true" styleClass="form-control" id="person">
								<f:selectItem itemValue="#{null}" itemLabel="-- Instruktor --" />
								<f:selectItems value="#{classRunController.allPerson}" var="p"
									itemLabel="#{p.email} | #{p.name} | #{p.firstName}"
									itemValue="#{p.id}" />
							</h:selectOneMenu>
							<h:message for="person" style="color:red" />
						</div>

						<!-- Kurs Raum -->
						<div class="form-group">
							<label for="room" class="control-label col-sm-3">#{msg['form.new.class.run.room']}</label>
							<h:selectOneMenu value="#{classRunController.roomId}"
								required="true" styleClass="form-control" id="room">
								<f:selectItem itemValue="#{null}" itemLabel="-- Raum --" />
								<f:selectItems value="#{classRunController.allRooms}" var="r"
									itemLabel="#{r.name}" itemValue="#{r.id}" />
							</h:selectOneMenu>
							<h:message for="room" style="color:red" />
						</div>

						<!-- Start Datum -->
						<div class="form-group">
							<label for="start" class="control-label col-sm-3">#{msg['form.new.class.run.start.date']}</label>
							<h:inputText pt:type="date" id="start" name="trip-start"
								value="#{classRunController.startDate}" min="2018-01-01"
								max="2022-12-31" styleClass="form-control">
								<f:validateRequired />
								<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
							</h:inputText>
							<h:message for="start" style="color:red" />
						</div>

						<!-- End Datum -->
						<div class="form-group">
							<label for="end" class="control-label col-sm-3">#{msg['form.new.class.run.end.date']}</label>
							<h:inputText pt:type="date" id="end" name="trip-start"
								value="#{classRunController.endDate}" min="2018-01-01"
								max="2022-12-31" styleClass="form-control">
								<f:validateRequired />
								<f:convertDateTime type="localDate" pattern="yyyy-MM-dd" />
							</h:inputText>
							<h:message for="end" style="color:red" />
						</div>

						<!-- Wochentag -->
						<div class="form-group">
							<label for="day" class="control-label col-sm-3">#{msg['form.new.class.run.room']}</label>
							<h:selectOneMenu value="#{classRunController.day}"
								required="true" styleClass="form-control" id="day">
								<f:selectItem itemValue="#{null}" itemLabel="-- Day --" />
								<f:selectItems value="#{classRunController.dayOfWeeks}" var="d"
									itemLabel="#{d}" itemValue="#{d.value}" />
							</h:selectOneMenu>
							<h:message for="day" style="color:red" />
						</div>

						<!-- Start Zeit -->
						<div class="form-group">
							<label for="time" class="control-label col-sm-3"><h:outputText
									value="#{msg['form.new.class.run.start.time']}" /></label>
							<h:inputText type="time" class="form-control" id="time"
								value="#{classRunController.startTime}"
								pt:placeholder="#{msg['form.new.class.run.start.time']}">
								<f:validateRegex
									pattern="^$|^(([01][0-9])|(2[0-3])):[0-5][0-9]$" />
								<f:validateRequired />
							</h:inputText>
							<h:message for="time" style="color:red" />
						</div>

						<!-- Dauer -->
						<div class="form-group">
							<label for="duration" class="control-label col-sm-3"><h:outputText
									value="#{msg['form.new.class.run.duration']}" /></label>
							<h:inputText type="time" class="form-control" id="duration"
								value="#{classRunController.duration}"
								pt:placeholder="#{msg['form.new.class.run.start.duration']}">
								<f:validateLongRange minimum="5" maximum="300" />
								<f:validateRequired />
							</h:inputText>
							<h:message for="duration" style="color:red" />
						</div>

						<div>
							<h:commandButton
								action="#{classRunController.createMultiClassRun}"
								value="#{msg['form.button.create']}"
								styleClass="btn btn-primary btn-lg btn-block button" />
						</div>

					</h:form>
				</div>
			</div>
		</ui:define>
	</ui:composition>

</h:body>

</html>