ManagementSys/src/main/java/ch/guggisberg/stefan/classAddStatisticsController/ClassAddStatisticsController.java
package ch.guggisberg.stefan.classAddStatisticsController;

import java.time.LocalDate;
import java.time.Month;
import java.time.Year;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.log4j.Logger;

import ch.guggisberg.stefan.base.BaseBean;
import ch.guggisberg.stefan.groupfitness.course.entities.ClassRun;
import ch.guggisberg.stefan.groupfitness.course.exceptions.WrongPersonException;
import ch.guggisberg.stefan.groupfitness.course.services.ClassRunService;
import ch.guggisberg.stefan.groupfitness.course.services.MonthlyPayrollService;
import ch.guggisberg.stefan.groupfitness.course.services.PersonService;
import ch.guggisberg.stefan.utils.monthlyJear.MonthlyYearFilter;

@Named
@SessionScoped
public class ClassAddStatisticsController extends BaseBean implements MonthlyYearFilter {

	private static final long serialVersionUID = -613855777758691745L;
	private static Logger log = Logger.getLogger(ClassAddStatisticsController.class);
	private static final Month[] MONTH = Month.values();

	@EJB
	private ClassRunService crs;
	
	@EJB
	private PersonService ps;

	@EJB
	private MonthlyPayrollService mp; 
	
	private ClassRun classRun;
	private String stringSelectedYear = Integer.toString(LocalDate.now().getYear());
	private int selectedMonth = LocalDate.now().getMonthValue();
	private boolean classBooked;
	
	// Nav
	private final static String NAVIGATE_TO_OVERVIEW_AMOUNT_OF_CUSTOMER = "/instructor/overviewAmountOfCustomer"; 
	private final static String NAVIGATE_TO_CLASS_ADD_STATISTICS = "/instructor/classAddStatistics";
	private final static String NAVIGATE_TO_MONTHLY_GRADUATION= "/instructor/monthlyGraduation";
	
	public List<ClassRun> getMyClassRuns(){
		
		return	crs.getMyClassRunsInDateRange(ps.getLoggedPerson().getId(), getFirstDay(stringSelectedYear, selectedMonth), getLastDay(stringSelectedYear, selectedMonth));
	}
	
	public List<ClassRun> getMyBookedClassRuns(){
		LocalDate selectedDate = LocalDate.of(Year.parse(stringSelectedYear).getValue(), selectedMonth, 1);
		return	crs.getMyClassRunsInDateRange(ps.getLoggedPerson().getId(),  getFirstDay(stringSelectedYear, selectedMonth), getLastDay(stringSelectedYear, selectedMonth));
	}

	public String search() {
		return NAVIGATE_TO_OVERVIEW_AMOUNT_OF_CUSTOMER;
	}
	
	public String filter() {
		return NAVIGATE_TO_MONTHLY_GRADUATION;
	}
	public String saveAmountCustomer(ClassRun cr) {
		classRun = cr;	
		return NAVIGATE_TO_CLASS_ADD_STATISTICS;
		}

	public String save()  {
		try {
			crs.addcustomerAmount(classRun);
			showGlobalMessage("messages.statistic.customer.saved");

		} catch (WrongPersonException e) {
			// Sollte nie passieren können.
			showGlobalErrorMessage("error.messages.hopla");
			log.error("Person versucht einen fremden Kurs updaten: ", e);
		}
		classRun=null;
		return NAVIGATE_TO_OVERVIEW_AMOUNT_OF_CUSTOMER;
	}
	
	public ClassRun getClassRun() {
		return classRun;
	}

	public void setClassRun(ClassRun classRun) {
		this.classRun = classRun;
	}

	public Month[] getMonth() {
		return MONTH;
	}

	
	public int getSelectedMonth() {
		return selectedMonth;
	}

	public void setSelectedMonth(int selectedMonth) {
		this.selectedMonth = selectedMonth;
	}
	public String getStringSelectedYear() {
		return stringSelectedYear;
	}

	public void setStringSelectedYear(String stringSelectedYear) {
		this.stringSelectedYear = stringSelectedYear;
	}

	public boolean isClassBooked() {
		return classBooked;
	}

	public void setClassBooked(boolean classBooked) {
		this.classBooked = classBooked;
	}
	
	
}

ManagementSys/src/main/webapp/instructor/classAddStatistics.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.book']}</ui:define>
		<ui:define name="content">
			<div class="container">
				<div class="col">
					<h2>
						<h:outputText value="#{msg['list.title.book']}" />
					</h2>
				</div>
				<div class="col">
					<h:form>
						<div class="form-check form-check-inline">
							<h:outputText
								value="#{classAddStatisticsController.classRun.date}" />
						</div>


						<div class="form-check form-check-inline">
							<h:outputText
								value="#{classAddStatisticsController.classRun.startTime}" />
						</div>

						<div class="form-check form-check-inline">
							<h:outputText
								value="#{classAddStatisticsController.classRun.kurs.name}" />

						</div>

						<div class="form-check form-check-inline">
							<h:inputText type="number" class="form-control"
								id="amountCustomer" value="#{classAddStatisticsController.classRun.amountCustomer}"
								pt:placeholder="#{msg['list.class.run.book.amount']}" />
							<h:message for="amountCustomer" style="color:red" />
						</div>

						<div class="form-check form-check-inline">

							<h:commandLink styleClass=""
								action="#{classAddStatisticsController.save}">
								<i class="material-icons"> save </i>


							</h:commandLink>
						</div>
					</h:form>


				</div>

			</div>
		</ui:define>

	</ui:composition>

</h:body>
</html>

ManagementSys/src/main/webapp/instructor/classesList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.myClasses']}</ui:define>
		<ui:define name="content">

			<div class="container"
				mx-autostyle="max-width: 600px; background: #ebeff2">
				<h2>
					<h:outputText value="#{msg['list.title.myClasses']}" />
				</h2>
				<div>

					<!--  Such Feld -->
					<div class="filter">
						<h:form class="form-inline mt-2 mt-md-0">
							<h:inputText class="form-control mr-sm-2" type="text"
								pt:placeholder="Search" aria-label="Search"
								value="#{classController.filter}" />
							

							<h:selectOneRadio value="#{user.favoriteBMW}">
   	<f:selectItem itemValue="335" itemLabel="BMW 335" />
   	<f:selectItem itemValue="316" itemLabel=" BMW 316" />
   	<f:selectItem itemValue="M3 SMG" itemLabel="BMW M3 SMG" />
</h:selectOneRadio>

<h:commandButton action="#{classController.search}"
								value="Filtern"
								styleClass="btn btn-outline-success my-2 my-sm-0" />



						</h:form>
					</div>

				</div>
				<!-- Tabelle -->
				<table class="table">
					<tbody>
						<thead class="thead-dark">
							<tr>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.datum']}" /></th>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.className']}" /></th>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.class.room']}" /></th>
								<th></th>
								<th></th>
							</tr>
						</thead>
						<h:form>
							<c:forEach var="myClassRun"
								items="#{instructorManagement.myClassRuns}">
								<tr>
									<td><h:outputText value="#{myClassRun.date}" /></td>
									<td><h:outputText value="#{myClassRun.kurs.nameDe}" /></td>
									<td><h:outputText value="#{myClassRun.room.nameDe}" /></td>
								</tr>
							</c:forEach>
						</h:form>

					</tbody>
				</table>
			</div>
		</ui:define>

	</ui:composition>

</h:body>
</html>

ManagementSys/src/main/webapp/instructor/monthlyGraduation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.monthly.graduation']}</ui:define>
		<ui:define name="content">

			<h2>
				<h:outputText value="#{msg['list.title.monthly.graduation']}" />
			</h2>
			<!-- Info Text -->
			<div class="alert alert-info" role="alert">
				Hier sind alle deine Kurse von der Vergangenheit bis heute! Mit dem
				<i class="material-icons"> delete </i> kannst du Kurse rauslöschen.

				Mit
				<p class="btn btn-outline-success my-2 my-sm-0">Stunden abgeben</p>
				Kannst du die Stunden der Fitnessleitung senden.

			</div>
			
			<!--  Stunde abgeben  -->
			<div class="alert alert-info">
				<h:form>
							Abgabe Zeitpunkt: #{monthlyPayrollController.deliveryDate}
							
							<h:commandButton
						action="#{monthlyPayrollController.createPayRollDoc()}"
						value="Stunden abgeben"
						styleClass="btn btn-outline-success form-check-inline " />
				</h:form>
			</div>
			
			<!-- Tabelle -->
			<table class="table">
				<tbody>
					<thead class="thead-dark">
						<tr>
							<th scope="col"><h:outputText
									value="#{msg['list.class.run.book.datum']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['list.class.run.book.time']}" /></th>

							<th scope="col"><h:outputText
									value="#{msg['list.class.run.className']}" /></th>
							<th scope="col"><h:outputText
									value="#{msg['list.class.run.book.amount']}" /></th>

							<th scope="col"><h:outputText
									value="#{msg['list.class.run.state']}" /></th>

							<th></th>
						</tr>
					</thead>

					<c:forEach var="myClassRun"
						items="#{monthlyPayrollController.multiClassRuns}">
						<h:form>
							<tr>
								<td><h:outputText value="#{myClassRun.date}" /></td>
								<td><h:outputText value="#{myClassRun.startTime}" /></td>
								<td><h:outputText value="#{myClassRun.kurs.nameDe}" /></td>
								<td><h:outputText value="#{myClassRun.amountCustomer}" /></td>
								<td><h:outputText value="#{myClassRun.state}" /></td>

								<td><h:commandLink styleClass=""
										action="#{monthlyPayrollController.removeFromMonthlyPayroll(myClassRun)}">
										<i class="material-icons"> delete </i>


									</h:commandLink></td>
							</tr>
						</h:form>
					</c:forEach>


				</tbody>
			</table>

		</ui:define>

	</ui:composition>

</h:body>
</html>

ManagementSys/src/main/webapp/instructor/overviewAmountOfCustomer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="title">#{msg['list.title.book']}</ui:define>
		<ui:define name="content">

			<div class="container"
				mx-autostyle="max-width: 600px; background: #ebeff2">
				<h2>
					<h:outputText value="#{msg['list.title.book']}" />
				</h2>
				<div>

					<!--  Such Feld -->
					<div class="filter">
						<h:form class="form-inline mt-2 mt-md-0">

							<!-- Monat -->
							<div class="form-check form-check-inline">
								<label for="start" class="control-label col-sm-3">#{msg['list.class.run.book.datum']}</label>
								<h:selectOneMenu
									value="#{classAddStatisticsController.selectedMonth}"
									class="form-control">
									<f:selectItems value="#{classAddStatisticsController.month}"
										var="m" itemLabel="#{m}" itemValue="#{m.value}" />
								</h:selectOneMenu>
							</div>

							<!-- Jahr -->
							<div class="form-check form-check-inline">
								<label for="year" class="control-label col-sm-3"><h:outputText
										value="#{msg['list.class.run.book.year']}" /></label>
								<h:inputText type="number" class="form-control" id="year"
									value="#{classAddStatisticsController.stringSelectedYear}"
									pt:placeholder="#{msg['list.class.run.book.year']}">
									<f:validateRegex pattern="^\d{4}$" />
									<f:validateRequired />
								</h:inputText>
								<h:message for="year" style="color:red" />
							</div>

							<div class="form-check form-check-inline">
								<h:commandButton
									action="#{classAddStatisticsController.search()}"
									value="Filtern"
									styleClass="btn btn-outline-success my-2 my-sm-0" />
							</div>
						</h:form>
					</div>

				</div>
				<!-- Tabelle -->
				<table class="table">
					<tbody>
						<thead class="thead-dark">
							<tr>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.book.datum']}" /></th>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.book.time']}" /></th>

								<th scope="col"><h:outputText
										value="#{msg['list.class.run.className']}" /></th>
								<th scope="col"><h:outputText
										value="#{msg['list.class.run.book.amount']}" /></th>

								<th></th>
							</tr>
						</thead>

						<c:forEach var="myClassRun"
							items="#{classAddStatisticsController.myClassRuns}">
							<h:form>
								<tr>
									<td><h:outputText value="#{myClassRun.date}" /></td>
									<td><h:outputText value="#{myClassRun.startTime}" /></td>
									<td><h:outputText value="#{myClassRun.kurs.name}" /></td>
									<td><h:outputText value="#{myClassRun.amountCustomer}" /></td>

									<td><h:commandLink styleClass=""
											action="#{classAddStatisticsController.saveAmountCustomer(myClassRun)}">
											<i class="material-icons"> edit </i>


										</h:commandLink></td>
								</tr>
							</h:form>
						</c:forEach>


					</tbody>
				</table>
			</div>
		</ui:define>

	</ui:composition>

</h:body>
</html>